### PR TITLE
Make indentation customizable

### PR DESCRIPTION
**Pull request by lberrymage**
This should resolve issue #2, which called for customizable indentation. I apologize if I missed something obvious as I'm not the keenest on JavaScript, but hopefully I contributed and/or learned something. I tried to conform to the indentation common to the rest of the project. There isn't much else to say about a four-line commit.

### CODE REVIEW

**Comment by dpilafian** [comment]
The update to the `defaults` map looks good.

Now to wire up the new `indent` option you created, just replace `3` with `settings.indent` in the line:
```
return htmlEntities(JSON.stringify(thing, null, 3)).replace(jsonLine, replacer);
```

If you then run `npm test` in the terminal, all the tests should still pass because the new `indent` option you created defaults to `3`.

**Comment by dpilafian** [comment]
Btw, you can interactively experiment with your changes in the **node** console by doing:
```
$ node
> .load pretty-print-json.js
> console.log(prettyPrintJson.toHtml({ id: 7,  color: 'red' }, { indent: 10 }));
```
This makes it easy to try different values for `indent` and verify the output looks correct.

**Comment by dpilafian** [comment]
Looks good!

**Comment by lberrymage** [comment]
Thanks for helping a Javascript noob dip their toes in the waters. I appreciate it.

**Pull request merged**
